{
 "title": "Healthplug - Linux Server",
 "description": "Metric view designed for a single system since some graphs overlay multiple queries.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(up{job=\"telegraf\"}, server_name)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(up{job=\"telegraf\", server_name=\"$server_name\"}, instance)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(disk_used_percent{fstype!=\"rootfs\", instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{instance=\"$instance\"}, interface)"
    }
   },
   {
    "name": "stack",
    "query": {
     "query": "label_values(docker_container_status_started_at{instance=\"$instance\"}, com_docker_stack_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "processes_zombies{instance=\"$instance\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Storage projection",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(disk_free{server_name=\"$server_name\",path!=\"/home\"} / delta(disk_used{server_name=\"$server_name\",path!=\"/home\"}[7d])) * 7",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Inbound Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{instance=\"$instance\"}[1h]))"
    }
   ]
  },
  {
   "title": "Outbound Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(net_bytes_sent{instance=\"$instance\"}[1h]))"
    }
   ]
  },
  {
   "title": "Traffic Errors and Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(net_err_in{instance=\"$instance\"}[1h])) +sum(increase(net_err_out{instance=\"$instance\"}[1h])) +sum(increase(net_drop_in{instance=\"$instance\"}[1h])) +sum(increase(net_drop_out{instance=\"$instance\"}[1h]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100-cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_buffered{instance=\"$instance\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "mem_cached{instance=\"$instance\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mem_free{instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_available{instance=\"$instance\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "mem_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_swap_total{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mem_swap_free{instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "mem_swap_total{instance=\"$instance\"} - mem_swap_free{instance=\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load1{job=\"telegraf\",instance=\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load5{job=\"telegraf\",instance=\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load15{job=\"telegraf\",instance=\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "processes_blocked{instance=\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "processes_dead{instance=\"$instance\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "processes_idle{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "processes_paging{instance=\"$instance\"}",
     "legendFormat": "Paging"
    },
    {
     "expr": "processes_running{instance=\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "processes_sleeping{instance=\"$instance\"}",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "processes_stopped{instance=\"$instance\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "processes_unknown{instance=\"$instance\"}",
     "legendFormat": "Unknown"
    },
    {
     "expr": "processes_zombies{instance=\"$instance\"}",
     "legendFormat": "Zombies"
    }
   ]
  },
  {
   "title": "Context Switch & Interrupt Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(kernel_context_switches{instance=\"$instance\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "rate(kernel_interrupts{instance=\"$instance\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Docker Run State",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_n_containers_running{instance=\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "docker_n_containers_stopped{instance=\"$instance\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "docker_n_containers_paused{instance=\"$instance\"}",
     "legendFormat": "Paused"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$instance\", device=~\"$disk_device\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{instance=\"$instance\", name=~\"$disk_device\"}[5m])",
     "legendFormat": "{{name}} Read"
    },
    {
     "expr": "rate(diskio_write_bytes{instance=\"$instance\", name=~\"$disk_device\"}[5m])",
     "legendFormat": "{{name}} Write"
    }
   ]
  },
  {
   "title": "Network Interface: $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk used - $disk_device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk capacity - $disk_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk write delta [per Minute] - $disk_device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(disk_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}[2m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Inodes Free - $disk_device",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_inodes_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "disk_inodes_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Inodes - $disk_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "disk_inodes_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_inodes_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Time Rate - $disk_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(diskio_read_time{instance=\"$instance\", name=\"$disk_device\", name!=\"All\"}[5m])",
     "legendFormat": "Read Time"
    },
    {
     "expr": "rate(diskio_write_time{instance=\"$instance\", name=\"$disk_device\", name!=\"All\"}[5m])",
     "legendFormat": "Write Time"
    },
    {
     "expr": "rate(diskio_io_time{instance=\"$instance\", name=\"$disk_device\", name!=\"All\"}[5m])",
     "legendFormat": "IO Time"
    }
   ]
  },
  {
   "title": "Disk IO Bytes Rate - $disk_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{instance=\"$instance\", name=\"$disk_device\", name!=\"All\"}[5m])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(diskio_write_bytes{instance=\"$instance\", name=\"$disk_device\", name!=\"All\"}[5m])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "Container Stack: $stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "repeat": "stack",
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "docker_container_status_started_at{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"} / 1000000"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(docker_container_cpu_usage_percent{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"}[3m])) by (com_docker_swarm_service_name)",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container Memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(docker_container_mem_usage_percent{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"}[3m])) by (com_docker_swarm_service_name)",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(docker_container_mem_usage{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"}[3m])) by (com_docker_swarm_service_name)",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container Net Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(docker_container_net_rx_bytes{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"}[3m])) by (com_docker_swarm_service_name)",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container Network Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(docker_container_net_tx_bytes{instance=\"$instance\",com_docker_stack_namespace=\"$stack\"}[3m])) by (com_docker_swarm_service_name)",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network Interface: $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "repeat": "interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Bytes Rate - $interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network Packets Rate - $interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Errors In Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Drop Out Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Error & Drop Rate - $interface",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "error_in"
    },
    {
     "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "error_out"
    },
    {
     "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "drop_in"
    },
    {
     "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "drop_out"
    }
   ]
  },
  {
   "title": "Drop In Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Errors Out Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}